name: push-docker

on:
  workflow_call:
    inputs:
      tag:
        description: "The docker image tag"
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: "The dockerhub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "The dockerhub token"
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: "The docker image tag"
        required: true
        type: string

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        variant: ["actions-template-sync"]
        target: ["prod", "dev"]

    steps:
      - name: checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: |
            andyaugustin/${{ matrix.variant }}
            ghcr.io/andreasaugustin/${{ matrix.variant }}
          tags: |
            type=semver,pattern={{raw}},value=${{ inputs.tag }}${{ matrix.target == 'dev' && '-dev' || '' }}
      - name: Build ${{ matrix.variant }}
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          target: ${{ matrix.target }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: install container test tools
        run: |
          echo "Install container tools"
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 \
            && chmod +x container-structure-test-linux-amd64 \
            && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
      - name: test docker image
        env:
          VARIANT: ${{ matrix.variant }}
          TAG: ${{ inputs.tag }}
          TARGET: ${{ matrix.target }}
        run: |
          echo "Run tests"
          SUFFIX=""
          if [ "$TARGET" = "dev" ]; then SUFFIX="-dev"; fi
          container-structure-test test \
            --image "andyaugustin/${VARIANT}:${TAG}${SUFFIX}" \
            --config docker-test-config.yml
          container-structure-test test \
            --image "ghcr.io/andreasaugustin/${VARIANT}:${TAG}${SUFFIX}" \
            --config docker-test-config.yml
      - name: push ${{ matrix.variant }}
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          target: ${{ matrix.target }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: andyAugustin/${{ matrix.variant }}
          readme-filepath: ./docs/DOCKER.md
          short-description: See https://github.com/${{ github.repository }} to have a look into the source code.
